#!/usr/bin/env bash

# Delete old binaries
rm /opt/go/bin/worker
rm /opt/go/bin/httpd
rm /opt/go/bin/envcheck

# Go get ElasticThought
go get -u -v -t github.com/tleyden/elastic-thought && \
go get -u -v -t github.com/tleyden/elastic-thought/cli/httpd && \
go get -u -v -t github.com/tleyden/elastic-thought/cli/worker && \
go get -u -v -t github.com/tleyden/elastic-thought/cli/envcheck

# Copy binaries to /usr/local/bin
cp /opt/go/bin/worker /usr/local/bin && \
cp /opt/go/bin/httpd /usr/local/bin && \
cp /opt/go/bin/envcheck /usr/local/bin
